AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - spec/dummy/bin/*
    - spec/dummy/config/initializers/*
    - spec/dummy/Rakefile
    - gemfiles/vendor/**/*
    - vendor/**/*

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - jsonschema_serializer.gemspec
    - spec/**/*

Metrics/LineLength:
  Max: 86
  Exclude:
    - jsonschema_serializer.gemspec

Style/FrozenStringLiteralComment:
  Exclude:
    - jsonschema_serializer.gemspec

Style/RedundantFreeze:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
