AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - spec/dummy/bin/*
    - spec/dummy/config/initializers/*
    - "*.gemspec"
    - Rakefile
    - spec/dummy/Rakefile
    - gemfiles/vendor/**/*
    - vendor/**/*

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 86

Style/RedundantFreeze:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
