AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/*
    - "*.gemspec"
    - Gemfile
    - Rakefile

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 90

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
