sudo: false

language: ruby

gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.4
  - 2.5.0
  - ruby-head

matrix:
  include:
    - rvm: 2.1.5
      gemfile: gemfiles/rails_4.gemfile
      env:
        - CODE_COVERAGE=true
    - rvm: jruby-9.0.5.0
      gemfile: Gemfile
      env:
        - RAILS_ENV=none
        - SKIP_RAILS=true

before_install: gem install bundler -v 1.16.1

# exported CC_TEST_REPORTER_ID global var in travis

before_script:
  - ./ci/before_script

script:
  - bundle exec rspec --format progress

after_script:
  - ./ci/after_script
