sudo: false

language: ruby

jobs:
  include:
    - rvm: 2.1.5
      gemfile: Gemfile
    - rvm: 2.2.7
      gemfile: Gemfile
    - rvm: 2.3.4
      gemfile: Gemfile
    - rvm: 2.4.1
      gemfile: Gemfile
    - rvm: 2.5.0
      gemfile: Gemfile
    - rvm: ruby-head
      gemfile: Gemfile
    - rvm: jruby-9.0.5.0
      gemfile: Gemfile

before_install: gem install bundler -v 1.16.1
